#!/usr/bin/env python3
# File generated by Grok (xAI).
"""
Recipe: fan out a large list across concurrent.futures workers with chunk_sequence
===============================================================================

``chunk_sequence`` splits any iterable into fixed-size list chunks. That is a
natural fit for ``concurrent.futures``: each worker receives one chunk, so you
avoid one-future-per-element overhead while still getting real parallelism.

This script builds a large integer sequence, partitions it with
``chunk_sequence``, and submits each chunk to a process pool (CPU-bound work) or
a thread pool (I/O-bound style work). Results are gathered with
``as_completed``.

Run from the repository root (editable install recommended)::

    pip install -e .
    python recipes/parallel_chunk_workers.py
    python recipes/parallel_chunk_workers.py --executor thread --size 500000 --chunk-size 25000


Why not ``Executor.map(..., chunksize=...)``?
---------------------------------------------

The stdlib already has a batching knob on ``Executor.map``::

    with ProcessPoolExecutor() as ex:
        for result in ex.map(process_item, data, chunksize=50_000):
            ...

That looks similar to this recipe at a glance, but the models differ in what is
chunked, what the worker sees, and what you get back.

**What ``chunksize`` actually does**

``map`` still applies the callable to **each individual element** of the
iterable. ``chunksize`` is only a scheduling / IPC optimization used mainly by
``ProcessPoolExecutor``: the parent packs that many *tasks* into one message so
pickling and inter-process traffic are cheaper. The worker still runs
``fn(item)`` once per item; it never receives a list of items as a single
argument. ``ThreadPoolExecutor`` largely ignores the idea of real batch work
here in the same way—the parameter exists for API parity.

**What ``chunk_sequence`` + ``submit`` does**

``chunk_sequence(data, size)`` builds **real list slices** of the input. Each
``executor.submit(process_chunk, chunk)`` hands that whole list to the worker
as **one** call. The unit of work is the batch: local aggregation, vectorized
logic, fewer Python function calls, and control over how large a piece of
state crosses the process boundary.

So:

* ``map(..., chunksize=N)`` ≈ "run this on every item; ship tasks in groups of N"
* ``chunk_sequence`` + ``submit`` ≈ "run this once per group of N items"

**Nature of the results: futures vs no futures**

``Executor.map`` returns an **iterator of return values**, not ``Future``
objects. Results are yielded in **input order** (completion order is hidden).
You cannot attach callbacks, cancel a particular slice of work, poll partial
progress, or mix heterogeneous callables. Exceptions surface when you iterate
to the failing item's position. There is no handle for "chunk 7 of 20".

This recipe instead holds a **list of ``Future``s—one per chunk**. That buys:

* **Out-of-order consumption** with ``as_completed``: fold partial stats as
  soon as any chunk finishes, without waiting for earlier indices.
* **Per-chunk lifecycle**: ``future.result()``, ``.exception()``,
  ``.add_done_callback(...)``, optional ``.cancel()`` while still pending.
* **Progress and accounting** tied to batches (e.g. "12/40 chunks done"), which
  maps cleanly onto logs, UIs, or early-exit heuristics.
* **Explicit result shape**: each future returns a small aggregate (here:
  count / min / max / sum of squares). You never materialize one result object
  per original element unless you want to.

The tradeoff is deliberate bookkeeping: you manage the futures yourself, and
if you need global order you must record chunk indices and reassemble. ``map``
is the simpler path when per-item results in order are enough and you do not
need futures at all.

**When to prefer which**

* Prefer ``map`` + ``chunksize`` for straightforward per-item transforms on a
  process pool where ordered results and minimal glue code matter more than
  batch-aware workers or future handles.
* Prefer ``chunk_sequence`` + ``submit`` when the worker should own a batch
  (local reduction, fewer round-trips of results, custom chunk metadata), or
  when you want real ``Future`` objects per unit of scheduled work.

This script demonstrates the second pattern.
"""

from __future__ import annotations

import argparse
import math
import time
from concurrent.futures import (
    Executor,
    Future,
    ProcessPoolExecutor,
    ThreadPoolExecutor,
    as_completed,
)
from typing import Iterable, Literal

from extralist import chunk_sequence


def process_chunk(chunk: list[int]) -> dict[str, float | int]:
    """CPU-bound-ish work on one chunk (sum of squares + simple stats).

    Defined at module level so ``ProcessPoolExecutor`` can pickle it.
    """
    if not chunk:
        return {"n": 0, "sum_sq": 0, "min": 0, "max": 0}
    sum_sq = 0
    lo = hi = chunk[0]
    for value in chunk:
        sum_sq += value * value
        if value < lo:
            lo = value
        if value > hi:
            hi = value
    return {"n": len(chunk), "sum_sq": sum_sq, "min": lo, "max": hi}


def submit_chunks(
    data: Iterable[int],
    chunk_size: int,
    executor: Executor,
) -> list[Future]:
    """Partition *data* and submit one future per chunk."""
    return [
        executor.submit(process_chunk, chunk)
        for chunk in chunk_sequence(data, chunk_size)
    ]


def run(
    size: int,
    chunk_size: int,
    max_workers: int | None,
    executor_kind: Literal["process", "thread"],
) -> None:
    data = range(size)
    # Eager materialization is optional; chunk_sequence accepts any iterable.
    # Using range keeps the driver light until chunks are built.

    pool_cls = ProcessPoolExecutor if executor_kind == "process" else ThreadPoolExecutor
    label = "ProcessPoolExecutor" if executor_kind == "process" else "ThreadPoolExecutor"

    print(f"items={size:,}  chunk_size={chunk_size:,}  executor={label}")
    if max_workers is not None:
        print(f"max_workers={max_workers}")

    t0 = time.perf_counter()
    with pool_cls(max_workers=max_workers) as executor:
        futures = submit_chunks(data, chunk_size, executor)
        n_chunks = len(futures)
        print(f"submitted {n_chunks:,} chunk(s)")

        total_n = 0
        total_sum_sq = 0
        global_min: int | None = None
        global_max: int | None = None

        for future in as_completed(futures):
            part = future.result()
            total_n += int(part["n"])
            total_sum_sq += int(part["sum_sq"])
            pmin, pmax = int(part["min"]), int(part["max"])
            global_min = pmin if global_min is None else min(global_min, pmin)
            global_max = pmax if global_max is None else max(global_max, pmax)

    elapsed = time.perf_counter() - t0

    expected_sum_sq = (size - 1) * size * (2 * size - 1) // 6 if size else 0
    rms = math.sqrt(total_sum_sq / total_n) if total_n else 0.0

    print(f"processed {total_n:,} items in {elapsed:.3f}s")
    print(f"min={global_min}  max={global_max}  rms≈{rms:.3f}")
    print(f"sum of squares ok: {total_sum_sq == expected_sum_sq}")


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Split a large sequence with extralist.chunk_sequence and process "
            "each chunk under concurrent.futures."
        )
    )
    parser.add_argument(
        "--size",
        type=int,
        default=1_000_000,
        help="Number of integers in the input sequence (default: 1_000_000)",
    )
    parser.add_argument(
        "--chunk-size",
        type=int,
        default=50_000,
        help="Items per chunk submitted to a worker (default: 50_000)",
    )
    parser.add_argument(
        "--max-workers",
        type=int,
        default=None,
        help="Pool size (default: executor's own default)",
    )
    parser.add_argument(
        "--executor",
        choices=("process", "thread"),
        default="process",
        help="Process pool for CPU work, thread pool for lighter demos (default: process)",
    )
    args = parser.parse_args(argv)

    if args.size < 0:
        parser.error("--size must be >= 0")
    if args.chunk_size < 1:
        parser.error("--chunk-size must be >= 1")

    run(args.size, args.chunk_size, args.max_workers, args.executor)


if __name__ == "__main__":
    main()
